### ISSUE TITLE
Font-face not generated for Cooper Hewitt

### ISSUE THREAD

**Issue by jacobbf** [superhi/editor-issues#23] opened 2019-09-24 22:07 UTC
**Describe the bug**
Editor does not add font-face definitions to "_fonts.css" for "Cooper Hewitt" font.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to editor
2. Add `font-face: Cooper Hewitt` to CSS file
3. Check "_fonts.css"
4. See that no `@font-face` has been added

**Expected behaviour**
`@font-face` rules defining the face with the relevant CDN links to be generated and included in "_font.css" as it is in the old editor.

**Screenshots**
_New Editor_
![font issue new](https://user-images.githubusercontent.com/23109850/65553951-27a5a900-def6-11e9-98b5-46508f7ac95a.gif)

_Old Editor_
![font issue old](https://user-images.githubusercontent.com/23109850/65553960-30967a80-def6-11e9-9587-1cb68da8b1bf.gif)

**Device (please complete the following information):**
- OS: macOS 10.14.6
- Browser: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by kdholland** [comment] 2019-09-24 22:11
@artcommacode I think you had flagged something like this previously - any idea what the issue is? 

I've noticed that the new editor can be more specific about fonts than the old one, but I also only thought we auto-loaded Google Fonts (which Cooper Hewitt is not.)

**Comment by artcommacode** [comment] 2019-09-25 08:00
Yep, what @kdholland said, we only autogenerate font files for those on Google Fonts. Previously the Editor also self-hosted a number of fonts but there were some issues with this implementation.

**Comment by kdholland** [comment] 2019-09-25 13:41
@jacobbf Sounds like this is a `wontfix` for the new editor - if this is a support issue please let them know the deal

**Comment by jacobbf** [comment] 2019-09-25 13:45
That's totally cool with me (on principal) but the Sally Hart project uses Cooper Hewitt which is autogenerated in the video - worried that since it's the first project in foundations dropping support for it will be a bit of an issue. Seems like the options are either to autogenerate Cooper Hewitt for now, rerecord that video or add some kind of supplement, just concerned since it's the very first project people do.

**Comment by kdholland** [comment] 2019-09-25 13:47
That's a really good point - thoughts on this @artcommacode ? Can we self host Cooper Hewitt or should we look into re-recording that video instead?

**Comment by artcommacode** [comment] 2019-09-25 13:48
Hmm is this the only case where this happens? Are there any other projects were we use self-hosted fonts?

**Comment by kdholland** [comment] 2019-09-25 13:50
Good question - @jacobbf can you do a roundup for the Foundations projects and see if there are more instances of this or if it's a one-off?

**Comment by jacobbf** [comment] 2019-09-25 13:52
Sure, I can take a look and see if there are other cases. In all the more recent courses we walk through uploading your own fonts and writing the CSS rules, so shouldn't be too bad.

**Comment by artcommacode** [comment] 2019-09-25 13:53
We also walk you through it in Week 6 of Foundation IIRC.

**Comment by jacobbf** [comment] 2019-09-25 21:49
Ok, as far as I can tell it's only in the first version of Sally Hart right at the beginning of the course - even when you redo the project with a lightbox it's using Helvetica instead.

**Closed as completed** 2021-01-26 14:09 UTC
Labels: question
