### ISSUE TITLE
In split preview, the header hides when you click a link with href="#"

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#17] opened 2019-07-31 15:18 UTC
**Describe the bug**
Header hides when you click a link with `href="#"`

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a link with `href="#"`
2. Click on it in the split preview
3. Header + URL bars hide (see GIF)

**Expected behaviour**

**Screenshots**
![hrefhide](https://user-images.githubusercontent.com/31701255/62224509-d3ae9600-b384-11e9-8a9a-ce59b2468411.gif)

**Device (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Google Chrome 75.0.3770.142

**Comment by artcommacode** [comment] 2019-08-01 08:44
Hmm this is some weird Ember thing. I can't reproduce in the editor-component itself but I _can_ in the Editor actual. I'll have to look into it a little more!

**Comment by kdholland** [comment] 2019-09-03 21:52
Just remembered this one after running into it again Foundations Week 8  (the prev/next links) - any luck with this one @artcommacode ?

(cc @jacobbf in case there's any support stuffs about this!)

**Comment by artcommacode** [comment] 2019-09-04 07:49
This is one of those issues with the current codebase that'll disappear when we move over to the new one. Closing for now, we can revisit it when we the new full-react editor is launched.

BTW those links should have `e.preventDefault()` on the listeners which'd prevent this from happening anyway!

**Closed as completed by artcommacode** 2019-09-04 07:49 UTC
Labels: bug
