### ISSUE TITLE
Duplicate File Names

### ISSUE THREAD

**Issue by jacobbf** [superhi/editor-issues#21] opened 2019-09-11 20:08 UTC
**Describe the bug**
After drag-and-drop uploading some images (specifically all the assets from the Uova Ajax + APIs project), the names of all files appeared in duplicate. Upon reloading they disappeared.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open web editor
2. Make new project
3. Drag-and-drop upload a collection of images
4. See duplicate file names

**Expected behaviour**
Non-duplicate file names

**Screenshots**
<img width="714" alt="Screen Shot 2019-09-10 at 5 12 48 PM" src="https://user-images.githubusercontent.com/23109850/64731149-99b9cf00-d4ae-11e9-916d-3788c159b988.png">
_On upload_

**Device (please complete the following information):**
 - OS: [e.g. macOS 10.14.6]
 - Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by kdholland** [comment] 2019-09-11 20:12
Hey @artcommacode - I've noticed this one a couple of times too. It seems to always happen when you're uploading multiple images (and so far it's only happened via drap and drop). The duplicates clear on reload.

Before:
![image](https://user-images.githubusercontent.com/31701255/64731231-beae4200-d4ae-11e9-82fe-281db759ef66.png)

After reload:
![image](https://user-images.githubusercontent.com/31701255/64731249-c8d04080-d4ae-11e9-9aae-cab8a83560fe.png)

**Comment by artcommacode** [comment] 2019-09-12 09:09
Hmm I can't reproduce that here even with multiple images and drag-and-drop. Either way though I can try and put some extra de-duplication logic in the editor!

**Comment by artcommacode** [comment] 2019-09-12 10:24
An hour of testing this and I can't reproduce it at all. I'm wondering if it's possible it's an API bug that only happens under load or something, what do you think @riklomas?

**Comment by artcommacode** [comment] 2019-09-12 10:51
Okay, I've pushed some code that should at least prevent duplicate files from being accepted from the API, hopefully that fixes it?! Let me know!

**Comment by jacobbf** [comment] 2019-09-12 14:39
Sounds good! Gonna take some time this afternoon to do some more thorough testing on Windows as well, so I'll let you know how it goes/if this pops up again.

**Comment by artcommacode** [comment] 2019-09-23 14:27
Closing this out for now, feel free to re-open if it rears it's head again!

**Closed as completed by artcommacode** 2019-09-23 14:27 UTC
Labels: bug
